// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(ContactMangerDbContext))]
    [Migration("20250629215114_StoredProcedure")]
    partial class StoredProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CountryName")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("4c5308b5-efa1-49ad-85c1-25aeaae52d21"),
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            CountryId = new Guid("8609cccd-54a7-4718-8d2a-3ba6f72389e7"),
                            CountryName = "Iran"
                        },
                        new
                        {
                            CountryId = new Guid("1dc09f1e-c61a-4438-96de-00acd31e93d6"),
                            CountryName = "Palestine"
                        },
                        new
                        {
                            CountryId = new Guid("b1a34b9b-ae18-4605-bb16-2a9a3957ab16"),
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            CountryId = new Guid("11829d03-f2b6-4d29-8d14-1000b61e72cf"),
                            CountryName = "Pakistan"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("2fbd9d9d-4c5d-43ca-9721-d6b11ee6bfc1"),
                            Address = "61 Vidon Hill",
                            CountryId = new Guid("4c5308b5-efa1-49ad-85c1-25aeaae52d21"),
                            DateOfBirth = new DateTime(1992, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dthame0@hp.com",
                            Gender = "Female",
                            PersonName = "Darelle Thame",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("bcc21781-33a6-4356-8875-d294cc26d7f2"),
                            Address = "6202 Porter Road",
                            CountryId = new Guid("b1a34b9b-ae18-4605-bb16-2a9a3957ab16"),
                            DateOfBirth = new DateTime(2007, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pblasik1@live.com",
                            Gender = "Female",
                            PersonName = "Pier Blasik",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("69e9b346-e785-423a-ad86-1c92c6457275"),
                            Address = "0179 Vahlen Pass",
                            CountryId = new Guid("1dc09f1e-c61a-4438-96de-00acd31e93d6"),
                            DateOfBirth = new DateTime(2006, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fhorsfield2@pagesperso-orange.fr",
                            Gender = "Female",
                            PersonName = "Faina Horsfield",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("13e64f65-0b6c-45b2-b18b-a8871e1af2d8"),
                            Address = "546 Chinook Pass",
                            CountryId = new Guid("11829d03-f2b6-4d29-8d14-1000b61e72cf"),
                            DateOfBirth = new DateTime(1998, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "abaddam3@narod.ru",
                            Gender = "Female",
                            PersonName = "Agathe Baddam",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("bbc4f831-e965-4dbe-a112-cbd618f9421a"),
                            Address = "6279 Maywood Point",
                            CountryId = new Guid("8609cccd-54a7-4718-8d2a-3ba6f72389e7"),
                            DateOfBirth = new DateTime(1991, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fgeerdts4@apache.org",
                            Gender = "Female",
                            PersonName = "Frances Geerdts",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("654016ab-9d9b-4658-bd49-2e7babfc6d56"),
                            Address = "87 Florence Center",
                            CountryId = new Guid("8609cccd-54a7-4718-8d2a-3ba6f72389e7"),
                            DateOfBirth = new DateTime(2000, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "memberson5@furl.net",
                            Gender = "Female",
                            PersonName = "Merline Emberson",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("32e660ff-2d44-4a96-9a4c-97c8b5a9fb0e"),
                            Address = "7 Doe Crossing Avenue",
                            CountryId = new Guid("8609cccd-54a7-4718-8d2a-3ba6f72389e7"),
                            DateOfBirth = new DateTime(1992, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sdunlap6@cyberchimps.com",
                            Gender = "Male",
                            PersonName = "Shurlock Dunlap",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("08384f70-af76-409c-bbdd-96afa3c19738"),
                            Address = "4762 Karstens Avenue",
                            CountryId = new Guid("1dc09f1e-c61a-4438-96de-00acd31e93d6"),
                            DateOfBirth = new DateTime(1997, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nreadhead7@artisteer.com",
                            Gender = "Male",
                            PersonName = "Nicolis Readhead",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("ff8ab986-3558-4f9b-91fe-31a03f291800"),
                            Address = "89 Oak Point",
                            CountryId = new Guid("4c5308b5-efa1-49ad-85c1-25aeaae52d21"),
                            DateOfBirth = new DateTime(2000, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rla8@psu.edu",
                            Gender = "Male",
                            PersonName = "Roderic La Torre",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("36ea9c3d-a426-4d09-9f46-e2b12e52b0e5"),
                            Address = "0 Bobwhite Hill",
                            CountryId = new Guid("8609cccd-54a7-4718-8d2a-3ba6f72389e7"),
                            DateOfBirth = new DateTime(2005, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dbooij9@ox.ac.uk",
                            Gender = "Male",
                            PersonName = "Dominik Booij",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("275a4927-8f67-476c-beb3-95e35ca3f8f7"),
                            Address = "65 Fordem Trail",
                            CountryId = new Guid("11829d03-f2b6-4d29-8d14-1000b61e72cf"),
                            DateOfBirth = new DateTime(1997, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cmcconigala@squarespace.com",
                            Gender = "Female",
                            PersonName = "Caril McConigal",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("4e8dac0d-12ce-44b8-a998-8aeaf245e53a"),
                            Address = "61682 Mifflin Plaza",
                            CountryId = new Guid("b1a34b9b-ae18-4605-bb16-2a9a3957ab16"),
                            DateOfBirth = new DateTime(2000, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tyeob@ustream.tv",
                            Gender = "Female",
                            PersonName = "Therese Yeo",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("0e32cf46-1b40-4bcd-bdd0-15b6e00c0aee"),
                            Address = "9 Duke Park",
                            CountryId = new Guid("11829d03-f2b6-4d29-8d14-1000b61e72cf"),
                            DateOfBirth = new DateTime(1999, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tcrucec@blogspot.com",
                            Gender = "Female",
                            PersonName = "Ted Cruce",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("8c5ebc57-c287-4d8b-ab92-aac34a13f3b9"),
                            Address = "5 Amoth Street",
                            CountryId = new Guid("8609cccd-54a7-4718-8d2a-3ba6f72389e7"),
                            DateOfBirth = new DateTime(2004, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "speakerd@printfriendly.com",
                            Gender = "Female",
                            PersonName = "Sheba Peaker",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("f8eea378-a640-4750-ae73-01941d9e5747"),
                            Address = "22 Homewood Street",
                            CountryId = new Guid("11829d03-f2b6-4d29-8d14-1000b61e72cf"),
                            DateOfBirth = new DateTime(1994, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "frhydderche@hibu.com",
                            Gender = "Male",
                            PersonName = "Franchot Rhydderch",
                            ReceiveNewsLetters = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
